MONGO:
  ADDRESS: '127.0.0.1'
  USERNAME: 'your-username'
  PASSWORD: 'your-passwd'
  PORT: 27017

REDIS:
  HOST: '127.0.0.1'
  PORT: 6379
  PASSWORD: 'your-passwd'

EMAIL:
  SENDER: 'sender-email'
  SENDER_PWD: 'sender_pwd'
  HOST_SERVER: 'smtp.163.com'
  RECEIVER:
    - 'receiver-email1'
    - 'receiver-email2'

AUTH:
  IDENTITY:
    - dev
    - prod
    - antx
    - your-identity
  SALT: 'your-salt'
